---
- name: Clone the git repository
  git: "repo={{ clone_url }} dest={{ dest }} version={{ version }} accept_hostkey=yes"
  notify: configure build

- name: Link the repo
  file: "src={{ dest + '/' + item.src }} dest={{ item.dest }} state=link"
  with_items: links
