---
- name: configure build
  command: "{{ configure_cmd }} chdir={{ dest }}"
  notify: do build
  when: build

- name: do build
  command: "{{ build_cmd }} chdir={{ dest }}"
  notify: install build

- name: install build
  become: yes
  command: "{{ install_cmd }} chdir={{ dest }}"
